-- SPDX-FileCopyrightText: Copyright (c) 2026 Objectionary.com
-- SPDX-License-Identifier: MIT

-- AUTO-GENERATED by scripts/gen-rule-data.py from objectionary/phino resources/*.yaml.
-- DO NOT EDIT BY HAND. Regenerate after phino's rules change.

import PhiConfluence.RuleSchema

/-!
# Normalization rules as structured data, generated from phino

The eleven rules as `RuleEntry` tags (types in PhiConfluence/RuleSchema.lean), emitted
by the fidelity-lock deriver `scripts/gen-rule-data.py`. CI (rule-data-in-sync)
regenerates this file from pinned phino and fails on any diff — keeping it identical.
-/

namespace PhiConfluence

/-- The φ-calculus normalization rules as structured, interpretable data. -/
def normalizationRuleData : List RuleEntry :=
  [ { name := "alpha", shape := .appForm, conds := [.alphaVoidOrdinal], rhs := .alphaRename }
  , { name := "copy", shape := .appForm, conds := [.slotVoid, .argXiFree, .argNf], rhs := .copyFill }
  , { name := "dc", shape := .appBot, conds := [], rhs := .bot }
  , { name := "dd", shape := .dispatchBot, conds := [], rhs := .bot }
  , { name := "dot", shape := .dispatchForm, conds := [.slotAttached, .valNf], rhs := .dotFeedback }
  , { name := "miss", shape := .appForm, conds := [.slotAbsent, .attrNotAlpha], rhs := .bot }
  , { name := "null", shape := .dispatchForm, conds := [.slotVoid], rhs := .bot }
  , { name := "over", shape := .appForm, conds := [.slotAttached, .attrNeRho], rhs := .bot }
  , { name := "phi", shape := .dispatchForm, conds := [.phiPresent, .slotAbsent], rhs := .phiExpand }
  , { name := "stay", shape := .appForm, conds := [.attrIsRho, .slotAttached], rhs := .formSame }
  , { name := "stop", shape := .dispatchForm, conds := [.slotAbsent, .phiAbsent, .noLambda], rhs := .bot } ]

end PhiConfluence
