-- SPDX-FileCopyrightText: Copyright (c) 2026 Objectionary.com
-- SPDX-License-Identifier: MIT

-- AUTO-GENERATED by scripts/gen-rules.py from objectionary/phino resources/*.yaml.
-- DO NOT EDIT BY HAND. Regenerate after phino's rules change.

import PhiConfluence.Render

/-!
# Normalization rules, as data, generated from phino

The eleven rules rendered from phino's `resources/*.yaml` the same way the
paper's reduction figure is (`phino explain`), including stripping `ξ`-free
side-conditions — so `copy` shows `nf(𝑒1)` only, as in the paper (phino's extra
`ξ`-free guard on `copy` is an operational anti-loop hack, not part of the
calculus; see docs/M0-spec.md). The proof relation `Step` is hand-written.
-/

namespace PhiConfluence

/-- The φ-calculus normalization rules, generated from phino's YAML. -/
def normalizationRules : List RuleSpec :=
  [ { name := "alpha", pattern := "⟦𝐵1, 𝜏1 ↦ ∅, 𝐵2⟧(𝜏2 ↦ 𝑒)", result := "⟦𝐵1, 𝜏1 ↦ ∅, 𝐵2⟧(𝜏1 ↦ 𝑒)", cond := "index(𝜏2) = domain(𝐵1)", wher := "" }
  , { name := "copy", pattern := "⟦ 𝐵1, 𝜏 ↦ ∅, 𝐵2 ⟧(𝜏 ↦ 𝑒)", result := "⟦ 𝐵1, 𝜏 ↦ 𝑒, 𝐵2 ⟧", cond := "xi-free(𝑒) and nf(𝑒)", wher := "" }
  , { name := "dc", pattern := "⊥(𝜏 ↦ 𝑒)", result := "⊥", cond := "", wher := "" }
  , { name := "dd", pattern := "⊥.𝜏", result := "⊥", cond := "", wher := "" }
  , { name := "dot", pattern := "⟦𝐵1, 𝜏 ↦ 𝑒1, 𝐵2⟧.𝜏", result := "𝑒2(ρ ↦ ⟦𝐵1, 𝜏 ↦ 𝑒1, 𝐵2⟧)", cond := "nf(𝑒1)", wher := "𝑒2 := contextualize(𝑒1, ⟦𝐵1, 𝜏 ↦ 𝑒1, 𝐵2⟧)" }
  , { name := "miss", pattern := "⟦𝐵⟧(𝜏 ↦ 𝑒)", result := "⊥", cond := "¬(𝜏 ∈ 𝐵) and ¬(α-attr(𝜏))", wher := "" }
  , { name := "null", pattern := "⟦𝐵1, 𝜏 ↦ ∅, 𝐵2⟧.𝜏", result := "⊥", cond := "", wher := "" }
  , { name := "over", pattern := "⟦𝐵1, 𝜏 ↦ 𝑒1, 𝐵2⟧(𝜏 ↦ 𝑒2)", result := "⊥", cond := "¬(𝜏 = ρ)", wher := "" }
  , { name := "phi", pattern := "⟦𝐵⟧.𝜏", result := "⟦𝐵⟧.φ.𝜏", cond := "φ ∈ 𝐵 and ¬(𝜏 ∈ 𝐵)", wher := "" }
  , { name := "stay", pattern := "⟦𝐵1, ρ ↦ 𝑒1, 𝐵2⟧(ρ ↦ 𝑒2)", result := "⟦𝐵1, ρ ↦ 𝑒1, 𝐵2⟧", cond := "", wher := "" }
  , { name := "stop", pattern := "⟦𝐵⟧.𝜏", result := "⊥", cond := "¬(𝜏 ∈ 𝐵) and ¬(φ ∈ 𝐵) and ¬(λ ∈ 𝐵)", wher := "" } ]

end PhiConfluence
