#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Objectionary.com
# SPDX-License-Identifier: MIT
"""
Generate PhiConfluence/Rules.lean from phino's resources/*.yaml.

This mirrors how the PAPER renders its reduction figure: phino's YAML rule files are
rendered by both the paper (via `phino explain`) and this project (this script). The
paper is the source of truth; phino is a secondary interpretation.

Like `phino explain`'s renderer (CST.withoutXi), this script STRIPS `xi` (ξ-free)
side-conditions, so the displayed table matches the paper's figure. The ξ-free guard
phino puts on `copy` is a phino-specific operational hack (it prevents a stack overflow
on ξ-containing values under eager contextualization); it is NOT in the paper, and is
unnecessary for confluence (our calculus is intentionally non-terminating). See
docs/M0-spec.md. `scripts/regen-rules.sh` runs this before every build.

Usage:
    gen-rules.py <phino-resources-dir> <output-Rules.lean>
"""
import sys

from phino_render import rules as rendered


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) != 3:
        raise SystemExit("Usage: gen-rules.py <phino-resources-dir> <output-Rules.lean>")
    res_dir, out = sys.argv[1], sys.argv[2]
    rules = rendered(res_dir)
    lines = [
        # REUSE-IgnoreStart
        "-- SPDX-FileCopyrightText: Copyright (c) 2026 Objectionary.com",
        "-- SPDX-License-Identifier: MIT",
        # REUSE-IgnoreEnd
        "",
        "-- AUTO-GENERATED by scripts/gen-rules.py from objectionary/phino resources/*.yaml.",
        "-- Not tracked by Git: `bash scripts/regen-rules.sh` regenerates it from pinned phino.",
        "",
        "import PhiConfluence.Render",
        "",
        "/-!",
        "# Normalization rules, as data, generated from phino",
        "",
        "The eleven rules rendered from phino's `resources/*.yaml` the same way the",
        "paper's reduction figure is (`phino explain`), including stripping `ξ`-free",
        "side-conditions — so `copy` shows `nf(𝑒1)` only, as in the paper (phino's extra",
        "`ξ`-free guard on `copy` is an operational anti-loop hack, not part of the",
        "calculus; see docs/M0-spec.md). The proof relation `Step` is hand-written.",
        "-/",
        "",
        "namespace PhiConfluence",
        "",
        "/-- The φ-calculus normalization rules, generated from phino's YAML. -/",
        "def normalizationRules : List RuleSpec :=",
    ]
    entries = []
    for r in rules:
        entries.append(
            "  { name := \"%s\", pattern := \"%s\", result := \"%s\", cond := \"%s\", wher := \"%s\" }"
            % (esc(r["name"]), esc(r["pattern"]), esc(r["result"]), esc(r["cond"]), esc(r["wher"]))
        )
    lines.append("  [ " + "\n  , ".join(e.strip() for e in entries) + " ]")
    lines.append("")
    lines.append("end PhiConfluence")
    lines.append("")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {out} with {len(rules)} rules")


if __name__ == "__main__":
    main()
