#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Objectionary.com
# SPDX-License-Identifier: MIT
"""
Generate PhiConfluence/Rules.lean from phino's resources/*.yaml.

This mirrors how the PAPER renders its reduction figure: phino's YAML rule files are
rendered by both the paper (via `phino explain`) and this project (this script). The
paper is the source of truth; phino is a secondary interpretation.

Like `phino explain`'s renderer (CST.withoutXi), this script STRIPS `xi` (ξ-free)
side-conditions, so the displayed table matches the paper's figure. The ξ-free guard
phino puts on `copy` is a phino-specific operational hack (it prevents a stack overflow
on ξ-containing values under eager contextualization); it is NOT in the paper, and is
unnecessary for confluence (our calculus is intentionally non-terminating). See
docs/M0-spec.md. Run this whenever phino's rules change.

Usage:
    gen-rules.py <phino-resources-dir> <output-Rules.lean>
"""
import sys, os, glob
import yaml


def rterm(x):
    return str(x)


def rcmp(x):
    if isinstance(x, dict):
        k = next(iter(x)); v = x[k]
        if k == "index":
            return f"index({rterm(v)})"
        if k == "length":
            return f"|{rterm(v)}|"
        return f"{k}({rterm(v)})"
    return rterm(x)


def rcond(w):
    if w is None:
        return ""
    if not isinstance(w, dict):
        return rterm(w)
    k = next(iter(w)); v = w[k]
    if k == "and":
        return " and ".join(p for p in (rcond(x) for x in v) if p)
    if k == "or":
        return " or ".join(p for p in (rcond(x) for x in v) if p)
    if k == "not":
        return "¬(" + rcond(v) + ")"
    if k == "in":
        return f"{rterm(v[0])} ∈ {rterm(v[1])}"
    if k == "nf":
        return f"nf({rterm(v)})"
    if k == "xi":
        return ""
    if k == "alpha":
        return f"α-attr({rterm(v)})"
    if k == "eq":
        return f"{rcmp(v[0])} = {rcmp(v[1])}"
    return f"{k}({rterm(v)})"


def rwhere(ws):
    parts = []
    for w in ws or []:
        meta = w.get("meta"); fn = w.get("function"); args = w.get("args", [])
        parts.append(f"{meta} := {fn}({', '.join(rterm(a) for a in args)})")
    return " and ".join(parts)


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    res_dir, out = sys.argv[1], sys.argv[2]
    rules = []
    for path in sorted(glob.glob(os.path.join(res_dir, "*.yaml"))):
        with open(path, encoding="utf-8") as f:
            d = yaml.safe_load(f)
        rules.append({
            "name": str(d["name"]),
            "pattern": str(d["pattern"]),
            "result": str(d["result"]),
            "cond": rcond(d.get("when")),
            "wher": rwhere(d.get("where")),
        })
    lines = [
        "-- SPDX-FileCopyrightText: Copyright (c) 2026 Objectionary.com",
        "-- SPDX-License-Identifier: MIT",
        "",
        "-- AUTO-GENERATED by scripts/gen-rules.py from objectionary/phino resources/*.yaml.",
        "-- DO NOT EDIT BY HAND. Regenerate after phino's rules change.",
        "",
        "import PhiConfluence.Render",
        "",
        "/-!",
        "# Normalization rules, as data, generated from phino",
        "",
        "The eleven rules rendered from phino's `resources/*.yaml` the same way the",
        "paper's reduction figure is (`phino explain`), including stripping `ξ`-free",
        "side-conditions — so `copy` shows `nf(𝑒1)` only, as in the paper (phino's extra",
        "`ξ`-free guard on `copy` is an operational anti-loop hack, not part of the",
        "calculus; see docs/M0-spec.md). The proof relation `Step` is hand-written.",
        "-/",
        "",
        "namespace PhiConfluence",
        "",
        "/-- The φ-calculus normalization rules, generated from phino's YAML. -/",
        "def normalizationRules : List RuleSpec :=",
    ]
    entries = []
    for r in rules:
        entries.append(
            "  { name := \"%s\", pattern := \"%s\", result := \"%s\", cond := \"%s\", wher := \"%s\" }"
            % (esc(r["name"]), esc(r["pattern"]), esc(r["result"]), esc(r["cond"]), esc(r["wher"]))
        )
    lines.append("  [ " + "\n  , ".join(e.strip() for e in entries) + " ]")
    lines.append("")
    lines.append("end PhiConfluence")
    lines.append("")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {out} with {len(rules)} rules")


if __name__ == "__main__":
    main()
