# SPDX-FileCopyrightText: Copyright (c) 2026 Objectionary.com
# SPDX-License-Identifier: MIT

name: build
on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-lean
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Test, build, and check axioms
        run: |
          pip install -r .github/requirements.txt
          make
